kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: route
  name: route
spec:
  replicas: 3
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: route
  template:
    metadata:
      labels:
        app: route
    spec:
      containers:
        - name: route
          image: routeio/route:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4001
            - containerPort: 4000
          resources:
            requests:
              cpu: 100m
              memory: 50M
            limits:
              cpu: 4000m
              memory: 4000Mi
          env:
            - name: route_cluster_seed
              value: "route"
      terminationGracePeriodSeconds: 30

---
# 客户端通过负载均衡连接 route
apiVersion: v1
kind: Service
metadata:
  name: route-loadbalancer
spec:
  type: NodePort
  selector:
    app: route
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30400
      name: client
---
#DNS srv 记录，route 节点互相发现使用此域名
apiVersion: v1
kind: Service
metadata:
  name: route
  labels:
    app: route
spec:
  clusterIP: None
  selector:
    app: route
  ports: